### ISSUE TITLE
Install root ca

### ISSUE THREAD

**Issue by wgtmpeters** [stylianosnicoletti/dotnet-certificate-tool#1]
Hi,

Could this also be used to also include a root CA certificate that the certificate has been signed with?
To avoid having to run the linux command to update the root ca store in linux?

**Comment by yohanb** [comment]
hi @wgtmpeters,
The api allows it but I'm not sure if it works.  I'll try it out and keep you updated.

**Comment by yohanb** [comment]
@wgtmpeters I added the functionality to specify the store name with the cli tool. It will allow you to install within Root and CertificateAuthority in the user's certificate store.
Please see the README for usage info.
Cheers!
