### ISSUE TITLE
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by shanefsl** [stylianosnicoletti/dotnet-certificate-tool#17]
I'm getting this error with the sample project (and my actual project) after running: docker run -v /tmp:/app/tmp docker-example --cert_filepath /app/tmp/cert.pfx --cert_password 'mypassword' --cert_thumbprint '<certthumbprint>'. 

> Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
>    at CommandLine.Text.HelpText.AddLine(StringBuilder builder, String value, Int32 maximumLength)
>    at CommandLine.Text.HelpText.AddPreOptionsLine(String value, Int32 maximumLength)
>    at CommandLine.Text.HelpText.AddPreOptionsLine(String value)
>    at CommandLine.Text.HelpText.DefaultParsingErrorsHandler[T](ParserResult`1 parserResult, HelpText current)
>    at CommandLine.Text.HelpText.<>c__DisplayClass39_0`1.<AutoBuild>b__2(HelpText current)
>    at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
>    at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Int32 maxDisplayWidth)
>    at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__1(IEnumerable`1 _, TextWriter writer)
>    at CSharpx.MaybeExtensions.Do[T1,T2](Maybe`1 maybe, Action`2 action)
>    at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__0(IEnumerable`1 errors)
>    at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
>    at CommandLine.Parser.DisplayHelp[T](ParserResult`1 parserResult, TextWriter helpWriter, Int32 maxDisplayWidth)
>    at CommandLine.Parser.MakeParserResult[T](ParserResult`1 parserResult, ParserSettings settings)
>    at CommandLine.Parser.ParseArguments(IEnumerable`1 args, Type[] types)
>    at CommandLine.ParserExtensions.ParseArguments[T1,T2](Parser parser, IEnumerable`1 args)
>    at GSoft.CertificateTool.Program.Main(String[] args) in /Users/yohan.belval/git/dotnet-certificate-tool/src/Program.cs:line 31
> ./docker-entrypoint.sh: line 36:     8 Aborted                 ./certificate-tool add -f ${cert_filepath} -t ${cert_thumbprint} -p ${cert_password}
> The following 0 certificate(s) are installed:

Any ideas? I can't see anything wrong with the values I'm putting in (or if there is, it's not a very friendly error message...)

**Comment by yohanb** [comment]
Hi @shanefsl, thanks for the issue.  Forgot to update the docker example since I removed the need for the thumbprint on the install.  Should be good now.
