### ISSUE TITLE
CurrentUser store not showing added certificates inside a Docker container.

### ISSUE THREAD

**Issue by sebastian-adamo** [stylianosnicoletti/dotnet-certificate-tool#22]
I have added a .pfx certificate via the tool to a Docker container and it shows that it installs successfully.

![image](https://user-images.githubusercontent.com/43730310/117974593-a64a9680-b325-11eb-977f-baf40d9bf4ba.png)

However, when I try to list all certificates in said user store in a .NET Core application, the store indicates that there are 0 certificates contained within it.

Could this be an issue with a difference in Linux user on Docker build vs Docker run?

**Comment by yohanb** [comment]
Hi @sebastian-adamo, are you sure the same user is being used for the install and list operations?
You can always check manually if the certificate is the in the `~/.dotnet/corefx/cryptography/x509stores/my/` folder.

**Comment by sebastian-adamo** [comment]
Hi @yohanb, thanks for the reply.
We have determined that the user installing the certificate during container build time is different to the one trying to access it in a .NET application during runtime. As such, I think that this is an issue with Docker.

**Comment by yohanb** [comment]
@sebastian-adamo [unless specified otherwise](https://docs.docker.com/engine/reference/builder/#user) the user should be root.
