### ISSUE TITLE
.net 7 update

### ISSUE THREAD

**Issue by Sumit10612** [stylianosnicoletti/dotnet-certificate-tool#30]
What is the plan for updating to net 7 ?
I see a PR for the same has been open for a while now.

**Comment by decarufe** [comment]
See: [Seeking New Maintainers for dotnet-certificat-tool](https://github.com/gsoft-inc/dotnet-certificate-tool/issues/34)

**Comment by stylianosnicoletti** [comment]
.net 8 support done
