### ISSUE TITLE
Maintainer interest

### ISSUE THREAD

**Issue by elonmallin** [stylianosnicoletti/dotnet-certificate-tool#36]
Hi, Im interested in becoming a maintainer so creating an issue here as suggested in #34 .

My main interest in this is doing the .net updates as the company Im working for is using this tool. I wont be developing this actively but I'd be happy to look at PRs with tests included to add new features as well.

Looking at the history it seems to be a manageable amount of issues coming in.

Let me know if this sounds ok for you @stylianosnicoletti

**Comment by stylianosnicoletti** [comment]
Hi Elon,
I sent you a collaborator invitation.  Please have a look. 
Thank you
