### ISSUE TITLE
Add Custom StoreLocation support

### ISSUE THREAD

**Issue by shoshins** [stylianosnicoletti/dotnet-certificate-tool#4]
**Suggestion:**
Please add the possibility to specify Store location (System.Security.Cryptography.X509Certificates.StoreLocation). 

**How it works right now:**
CurrentUser store location is hardcoded.
Example:
`
var store = new X509Store(storeName, StoreLocation.CurrentUser);
`

**Comment by yohanb** [comment]
Hi @shoshins,
I'm not sure other store locations are supported under Linux distros.  Have you tried it?

**Comment by shoshins** [comment]
Yes, Linux does not allow us to use LocalMachine storage. 

`Unix LocalMachine X509Stores are read-only for all users.`

But I was able to install the certificate on macOS for example. And also this tool can be used on Windows computers/servers too. I suppose that .net core is a universal thing).

Maybe some other Unix-based platforms (except Linux, like macOS) allow this.
