### ISSUE TITLE
When 

### ISSUE THREAD

**Issue by ionutcalin** [stylianosnicoletti/dotnet-certificate-tool#6]

**Comment by ionutcalin** [comment]
The pfx is a container of certificates, it can contain  the personal certificate, personal private key + all the CA authority chain that issued/signed that certificate.
It will be extremely useful if this dotnet cli tool will:
1) When give a pfx in the input, will look if the certificates of the signing CA's are embedded in the pfx and automatically add them (if not already present) in the appropriate store (CertificateAuthority or Root) . Eventually this feature can be enabled (opt-in) with a flag in the parameters of the tool
2) When give a .cer or .crt in the input than don't ask for a -p (password) as a mandatory inout parameter

PS I'm using the tool now from Docker-Compose feature of Visual Studio and the two changes from above would be extremely helpful

**Comment by yohanb** [comment]
I'm sorry @ionutcalin I've been pretty busy these last few days.  I can try to find some time this week to look into this.
